// src/data/products.js

const products = [
  // Everyday cheap items
  { id: 1, name: "Pen", price: 1, image: "" },
  { id: 2, name: "Notebook", price: 3, image: "" },
  { id: 3, name: "Water Bottle", price: 5, image: "" },
  { id: 4, name: "Coffee Mug", price: 8, image: "" },
  { id: 5, name: "T-Shirt", price: 15, image: "" },
  { id: 6, name: "Cap", price: 20, image: "" },
  { id: 7, name: "Backpack", price: 45, image: "" },
  { id: 8, name: "Sneakers", price: 90, image: "" },
  { id: 9, name: "Smart Light Bulb", price: 30, image: "" },
  { id: 10, name: "Bluetooth Earbuds", price: 60, image: "" },
  { id: 11, name: "Smartwatch", price: 150, image: "" },
  { id: 12, name: "iPhone 16 Pro", price: 1499, image: "" },
  { id: 13, name: "iPad Air", price: 999, image: "" },
  { id: 14, name: "MacBook Air M3", price: 1399, image: "" },
  { id: 15, name: "iMac 24-inch", price: 1599, image: "" },
  { id: 16, name: "Gaming PC", price: 2200, image: "" },
  { id: 17, name: "Electric Scooter", price: 850, image: "" },
  { id: 18, name: "Drone", price: 1200, image: "" },
  { id: 19, name: "Camera DSLR", price: 1800, image: "" },
  { id: 20, name: "PlayStation 5", price: 500, image: "" },
  { id: 21, name: "Xbox Series X", price: 500, image: "" },
  { id: 22, name: "Smart TV 55-inch", price: 1000, image: "" },
  { id: 23, name: "Apple Vision Pro", price: 3499, image: "" },
  { id: 24, name: "Electric Bike", price: 2500, image: "" },
  { id: 25, name: "Home Theater System", price: 1200, image: "" },
  { id: 26, name: "Luxury Watch", price: 6000, image: "" },
  { id: 27, name: "Gaming Setup (Full)", price: 8000, image: "" },
  { id: 28, name: "Diamond Ring", price: 10000, image: "" },
  { id: 29, name: "Used Car", price: 15000, image: "" },
  { id: 30, name: "Tesla Model 3", price: 42000, image: "" },
  { id: 31, name: "Tesla Model S", price: 95000, image: "" },
  { id: 32, name: "Luxury Apartment", price: 500000, image: "" },
  { id: 33, name: "Private Jet", price: 45000000, image: "" },
  { id: 34, name: "Mega Yacht", price: 250000000, image: "" },
];

export default products;